#ifndef _VERSION_H_
#define _VERSION_H_

#define PLUGINYEAR		2025
#define PLUGINMAJOR 	1
#define PLUGINMINOR 	0
#define PLUGINREVISION	1
#define PLUGINBUILD		0

#define _PLUGINVERSIONSTR2(x)	#x
#define _PLUGINVERSIONSTR(x)	_PLUGINVERSIONSTR2(x)
#define PLUGINVERSION			_PLUGINVERSIONSTR(PLUGINMAJOR.PLUGINMINOR.PLUGINREVISION.PLUGINBUILD)

#endif // _VERSION_H_
